### PR TITLE
sort index before comparing

### PR DESCRIPTION
**Pull request by wkitlasten**
Lines and polygons dfs needed to be sorted before comparing index.
(I suck at git so hopefully this works. Let me know if I need to do something different.)

### CODE REVIEW

**Comment by mwtoews** [comment]
There's not any requirement that line segment indexes need to be sorted in any particular way, but I'd prefer them to remain the same as the source input (in case other properties from the shapefile need to be brought over). It shouldn't be too difficult to sort or re-index the inputs before? Try (e.g.):

    n = SurfaceWaterNetwork.from_lines(lines, polygons.reindex(index=lines.index))

**Comment by wkitlasten** [comment]
Lines index needs to be sorted before creating segments gdf. Unfortunately I am testing it on a very large network so it didn't fail until later. I am now getting a swn for the entire nzRec2_v5.gdb.

**Comment by wkitlasten** [comment]
Makes sense, but the following was failing, even though polygons and lines were from the same source:

(polygons.index == lines.index).all())

Until I sorted them, then it worked.

**Comment by wkitlasten** [comment]
But the reindex seems to work fine. Thanks.

**Pull request closed without merging**
